In [1]:
import tensorflow as tf
import numpy as np
import time

In [2]:
# placeholders
start_t = time.time()
with tf.device('/gpu:0'):
    x = tf.placeholder(tf.float32,shape=(1024,1024))
    y = tf.matmul(x,x)
    rand_array = np.random.rand(1024,1024)
    
    with tf.Session() as session:
        #rand_array = np.random.rand(1024,1024)
        print(session.run(y,feed_dict={x: rand_array}))
end_t = time.time()
print('\ntime taken = ',(end_t-start_t)*1000,' ms')

[[ 256.26263428  250.16459656  251.8004303  ...,  242.88000488
   246.24009705  253.70085144]
 [ 253.29797363  246.02438354  251.85113525 ...,  240.39865112
   244.47224426  251.759552  ]
 [ 255.03149414  249.57252502  249.49327087 ...,  239.60955811
   246.07211304  251.49026489]
 ..., 
 [ 261.05078125  258.02038574  256.20080566 ...,  253.19392395
   250.76153564  265.51721191]
 [ 264.75878906  259.07385254  265.75817871 ...,  252.18055725
   259.06143188  272.3961792 ]
 [ 256.12451172  253.3157959   250.20796204 ...,  245.39572144
   248.12191772  257.39718628]]

time taken =  1196.1801052093506  ms


In [3]:
# placeholders
x2 = tf.placeholder(tf.float32,shape=(1024,1024))
y2 = tf.matmul(x2,x2)
rand_array2 = np.random.rand(1024,1024)

with tf.Session() as session:
    #rand_array = np.random.rand(1024,1024)
    z =(session.run(y2,feed_dict={x2: rand_array2})
        

SyntaxError: unexpected EOF while parsing (<ipython-input-3-3ac4ce7396f9>, line 9)

In [4]:
#3

a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

[[ 22.  28.]
 [ 49.  64.]]


In [5]:
# variables

# create two varables
w = tf.Variable(tf.random_normal([784,200],stddev=0.35),name='w')
b = tf.Variable(tf.zeros([200]),name='b')

int_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(int_op)
    m = tf.add(w,b)
    print(m)

Tensor("Add:0", shape=(784, 200), dtype=float32)


In [6]:
# initializing from an other variable

# create a variable with a random value
w1 = tf.Variable(tf.random_normal([784,200],stddev=0.35),name='w1')
# copy variable
w2 = tf.Variable(w1.initialized_value(),name='w2')
w1_twice = tf.Variable(w1.initialized_value()*2,name='w1_twice')

In [10]:
# save and restore

In [17]:
# comparison of numpy and tensorflow

import numpy as np

a = np.zeros((2,2))
b = np.zeros((2,2))

print(np.sum(b,axis=1),' = sum')

print(a.shape,' = shape of a')

display(np.reshape(a,(1,4)))

[ 0.  0.]  = sum
(2, 2)  = shape of a


array([[ 0.,  0.,  0.,  0.]])

In [18]:
# same in tensorflow
 
tf.InteractiveSession()

a = tf.zeros((2,2))
b = tf.zeros((2,2))

print(tf.reduce_sum(b,reduction_indices=1).eval(),' = sum')

display(a.get_shape(),' = shape of a')

display(tf.reshape(a,(1,4)).eval())

[ 0.  0.]  = sum


TensorShape([Dimension(2), Dimension(2)])

' = shape of a'

array([[ 0.,  0.,  0.,  0.]], dtype=float32)