In [26]:
import numpy as np

In [27]:
#slicing
n = [6,7,8]
n[0:2]

[6, 7]

In [28]:
#slicing in numpy
array = np.array([5,5,6,9])
array[0:2]

array2 = np.array([[3,2,4],[2,5,7],[7,5,2]]) #creating a 3x3 matrix
array3 = np.array([[3,3,5],[5,5,7],[8,5,2]])
print(array2,'\t',array2[-1],'\n\n',array2[:,1:3])

#iteration
for row in array2:
    print(row)

for cell in array2.flat:
    print(cell)
    
#stacking
print('\n',np.vstack((array2,array3)),'= vstack') #virtical stacking
print('\n',np.hstack((array2,array3)),'= hstack') #horizontal stacking
print('\n',np.vsplit(array2,3),'= vsplit')

[[3 2 4]
 [2 5 7]
 [7 5 2]] 	 [7 5 2] 

 [[2 4]
 [5 7]
 [5 2]]
[3 2 4]
[2 5 7]
[7 5 2]
3
2
4
2
5
7
7
5
2

 [[3 2 4]
 [2 5 7]
 [7 5 2]
 [3 3 5]
 [5 5 7]
 [8 5 2]] = vstack

 [[3 2 4 3 3 5]
 [2 5 7 5 5 7]
 [7 5 2 8 5 2]] = hstack

 [array([[3, 2, 4]]), array([[2, 5, 7]]), array([[7, 5, 2]])] = vsplit


In [29]:
# boolean arrays
bool_array = np.arange(16).reshape(4,4)  #creating a 4x4 matrix

print(bool_array,'4x4 matrix\n')
print(bool_array>6,'= boolean array')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 4x4 matrix

[[False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]] = boolean array


In [30]:
temp_array = bool_array < 5

In [31]:
bool_array[temp_array]

array([0, 1, 2, 3, 4])

In [32]:
temp_array

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [33]:
temp_array.astype(int)

array([[1, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
a = np.array([2,3,5,6])
a[3]

6

In [35]:
b = np.random.random((5,5))
b

array([[ 0.50012835,  0.90461214,  0.0376947 ,  0.7255538 ,  0.28527748],
       [ 0.10820146,  0.96119809,  0.93893007,  0.70265819,  0.26737637],
       [ 0.42990526,  0.30660307,  0.24687945,  0.01515704,  0.43360337],
       [ 0.95201684,  0.98415848,  0.03155105,  0.94888682,  0.51059981],
       [ 0.77257497,  0.75214411,  0.02824907,  0.56136487,  0.31717818]])