In [1]:
#importing lib
import numpy as np
import time 
import sys

In [2]:
# Memory usage
# python list
py_list = range(1000) #python list
print('python list takes',sys.getsizeof(7)*len(py_list),'bytes') # 7* can be any number

#numpy array
np_array = np.arange(1000)
print('numpy array takes',np_array.size*np_array.itemsize,'bytes')
np_array.itemsize,np_array.size

python list takes 28000 bytes
numpy array takes 4000 bytes


(4, 1000)

In [3]:
# Time taken by numpy and python list
array_size = 10000000 # 10 million ,a consideribly large size helps understand the time difference better

# Python list
py_list1 = range(array_size)
py_list2 = range(array_size)

py_start = time.time() # capturing a time instance(similar to a stop watch)
result = [(x + y) for x,y in zip(py_list1,py_list2)] # performing addiiton of the two lists
py_end = time.time() # capturing a second  time instance(the difference gives the time taken for the operation)
print('time taken for python list :',(py_end - py_start) * 1000,'ms') # By default the time is in seconds *1000 coverts it to milliseonds

# numpy array
np_array1 = np.arange(array_size)
np_array2 = np.arange(array_size)

np_start = time.time()
result = np_array1 + np_array2
np_end = time.time()
print('time taken for numpy array :',(np_end - np_start) * 1000,'ms')

time taken for python list : 2345.658779144287 ms
time taken for numpy array : 273.99659156799316 ms


In [4]:
# Creating arrays
array_a = np.array([1,2,3])   # create 1D array
array_b = np.array([[2,4,5],[5,3,9]],dtype=float)   # creating a 2x3 matrix with values as type float
array_c = np.array([[(3.2,5,6),(4.1,7,9)],[(2,4,5),(7,4,9)]],dtype=float)   # creating multple arrays with data type as float

print(array_a,'= array a (1D array)\n')
print(array_b,'= array b (2D array)\n')
print(array_c,'= array c (multiple arrays)')

[1 2 3] = array a (1D array)

[[ 2.  4.  5.]
 [ 5.  3.  9.]] = array b (2D array)

[[[ 3.2  5.   6. ]
  [ 4.1  7.   9. ]]

 [[ 2.   4.   5. ]
  [ 7.   4.   9. ]]] = array c (multiple arrays)


In [5]:
# Creating arrays with place holders

zeros_array = np.zeros((3,3))  # creates a 3x3 matrix with zeros
ones_array = np.ones((3,4))    # creates a 3x4 array with ones
empty_array = np.empty((3,4))  # creates an empty array with dimensions 3x4
eye_array = np.eye(3)          # creates an identity matrix of 3x3
random_array = np.random.random((3,2)) # creates a 3x3 array with random variables
full_array = np.full((2,2),6)  #creates an array with constant number 6

print(zeros_array,'= zeros array \n')
print(ones_array,'= ones array\n')
print(empty_array,'= empty array\n')
print(eye_array,'= identity array\n')
print(random_array,'= random array \n')
print(full_array,'= constant array \n')

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] = zeros array 

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] = ones array

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] = empty array

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] = identity array

[[ 0.78988412  0.25125293]
 [ 0.06922745  0.58871348]
 [ 0.70234489  0.92483962]] = random array 

[[6 6]
 [6 6]] = constant array 



In [6]:
# Array inspection

ins_array = np.array([[3,2,1,4],[7,5,9,2]])   # creating a 2x4 array(inspection array)

print(ins_array,'= Array')  #displaying the array
print('\n',ins_array.shape,'= shape the array / dimensions of the array\n')
print(len(ins_array),'length of the array\n')
print(ins_array.ndim,'= number of array dimensions\n')
print(ins_array.size,'= number of array elements\n')
print(ins_array.dtype,'= data type of the array elements\n')
print(ins_array.dtype.name,'= name of the data type\n')
print(ins_array.astype(float),'= convert an array to a different type\n') 

[[3 2 1 4]
 [7 5 9 2]] = Array

 (2, 4) = shape the array / dimensions of the array

2 length of the array

2 = number of array dimensions

8 = number of array elements

int32 = data type of the array elements

int32 = name of the data type

[[ 3.  2.  1.  4.]
 [ 7.  5.  9.  2.]] = convert an array to a different type



In [9]:
# Arithmetic opreations

array_a = np.array([[2,3],[5,7]])  # creating array A 2x2
array_b = np.array([[4,2],[6,8]])  # creating array B 2x2

print(array_a,' = array A\n')
print(array_b,' = array B\n')

print(array_a - array_b,' = subtraction\n')  #subtracting two arrays normal operation
print(np.subtract(array_a,array_b),'= subtraction using numpy\n')

print(array_a + array_b,' = addition\n')  #addition two arrays normal operation
print(np.add(array_a,array_b),'= addition using numpy\n')

print(array_a / array_b,' = division\n')  #dividing two arrays normal operation
print(np.divide(array_a,array_b),'= division using numpy\n')

print(array_a * array_b,' = multiplication\n')  #multiplying two arrays normal operation
print(np.multiply(array_a,array_b),'= multiplication using numpy\n')

[[2 3]
 [5 7]]  = array A

[[4 2]
 [6 8]]  = array B

[[-2  1]
 [-1 -1]]  = subtraction

[[-2  1]
 [-1 -1]] = subtraction using numpy

[[ 6  5]
 [11 15]]  = addition

[[ 6  5]
 [11 15]] = addition using numpy

[[ 0.5         1.5       ]
 [ 0.83333333  0.875     ]]  = division

[[ 0.5         1.5       ]
 [ 0.83333333  0.875     ]] = division using numpy

[[ 8  6]
 [30 56]]  = multiplication

[[ 8  6]
 [30 56]] = multiplication using numpy



In [12]:
print(array_a,'= array A\n')

print(np.exp(array_a),' = exponentitation\n')   # returns the exponent of the array
print(np.sqrt(array_a),'= Square root\n')       # returns the square root of the array
print(np.sin(array_a),' = sines\n')             # prints the sines of the array
print(np.cos(array_a),' = cosine\n')            # returns element wise cosine
print(np.log(array_a),' = natural logarithm\n') # returns element wise natural logarithm
print(array_a.dot(2),' = dot product\n')        # dot product of the array

[[2 3]
 [5 7]] = array A

[[    7.3890561     20.08553692]
 [  148.4131591   1096.63315843]]  = exponentitation

[[ 1.41421356  1.73205081]
 [ 2.23606798  2.64575131]] = Square root

[[ 0.90929743  0.14112001]
 [-0.95892427  0.6569866 ]]  = sines

[[-0.41614684 -0.9899925 ]
 [ 0.28366219  0.75390225]]  = cosine

[[ 0.69314718  1.09861229]
 [ 1.60943791  1.94591015]]  = natural logarithm

[[ 4  6]
 [10 14]]  = dot product



In [17]:
# Comparision

print(array_a,' = array A\n')
print(array_b,' = array B\n')

print(array_a == array_b,' = comparison\n')  # element wise comparison
print(array_a<5 ,' = comparison\n')          # prints true for all values < 5
print('array A and array B are equal = ',np.array_equal(array_a,array_b))  # array wise comparison

[[2 3]
 [5 7]]  = array A

[[4 2]
 [6 8]]  = array B

[[False False]
 [False False]]  = comparison

[[ True  True]
 [False False]]  = comparison

array A and array B are equal =  False


In [21]:
# Aggregate functions

print(array_a,' = array A\n')                   # display array
print(array_a.sum(),'--- sum\n')                # array wise sum 
print(array_a.min(),'--- minimum value\n')      # array wise minimum value
print(array_a.max(axis=0),'--- max value\n')    # maximum value of an array row
print(array_a.mean(),'--- mean\n')              # mean of the array
print(array_a.std(),'--- std\n')                # standard deviation of the array    

[[2 3]
 [5 7]]  = array A

17 --- sum

2 --- minimum value

[5 7] --- max value

4.25 --- mean

1.92028643697 --- std



In [85]:
# sorting arrays

rand_array =np.random.random((8,3))                                      # Creating a 8x1 array of random variables

print(rand_array,' = random variable array\n')                           # displaying array
print(np.sort(rand_array,axis=0),' = sorting of array colom wise')      # By default the sorting is applied on row wise axis = 1 changes it to colom wise   

[[ 0.99521904  0.83689664  0.23666683]
 [ 0.57935315  0.27533265  0.16985335]
 [ 0.53881151  0.87263035  0.92429208]
 [ 0.6640889   0.89837485  0.05847144]
 [ 0.33708667  0.9399604   0.08411445]
 [ 0.35695102  0.12867803  0.99343711]
 [ 0.74057631  0.17093348  0.13444435]
 [ 0.21916249  0.9092303   0.56866963]]  = random variable array

[[ 0.21916249  0.12867803  0.05847144]
 [ 0.33708667  0.17093348  0.08411445]
 [ 0.35695102  0.27533265  0.13444435]
 [ 0.53881151  0.83689664  0.16985335]
 [ 0.57935315  0.87263035  0.23666683]
 [ 0.6640889   0.89837485  0.56866963]
 [ 0.74057631  0.9092303   0.92429208]
 [ 0.99521904  0.9399604   0.99343711]]  = sorting of array colom wise


In [102]:
# Subsetting

array_a = np.random.random(9)                         # create an array of 9 elements
print(array_a,' = array A\n')                         # Display array
print('the 7th element is = ',array_a[6])             # selecting the 7th element in array A

array_b = np.random.randint(5, size=(2,5))            # create random array 
print(array_b,' = array B\n')                         # Display array
print('2nd coloum 2nd row = ',array_b[1,1])           # selecting the element from 2nd row 2nd coloumn

[ 0.76799325  0.01631997  0.1378917   0.85911524  0.176175    0.05097026
  0.53335974  0.59335999  0.00637776]  = array A

the 7th element is =  0.533359742154
[[0 3 0 0 2]
 [1 2 3 1 2]]  = array B

2nd coloum 2nd row =  2
