In [1]:
import numpy as np
import time
import sys

In [2]:
#memory allocation/usage
#ex1 python list
py_list = range(1000) #python list
print('python list takes',sys.getsizeof(3)*len(py_list),'bytes') # 3* can be any number
#ex1.1 numpy 
np_array = np.arange(1000) # a range similar to a pylist
print('numpy array takes',np_array.size*np_array.itemsize,'bytes')

python list takes 28000 bytes
numpy array takes 4000 bytes


In [3]:
#time difference b/w python and numpy
array_size = 10000000 # 10 million 

#python list
py_list1 = range(array_size)
py_list2 = range(array_size)

py_start = time.time()
result = [(x + y) for  x,y in zip(py_list1,py_list2)]
py_end = time.time()
print('time taken by python list : ',(py_end-py_start)*1000,'ms')

#numpy array
np_array1 = np.array(array_size)
np_array2 = np.array(array_size)

np_start = time.time()
result = np_array1 + np_array2
np_end = time.time()
print('time taken by numpy       : ',(np_end-np_start)*1000,'ms')

time taken by python list :  3468.859910964966 ms
time taken by numpy       :  296.8881130218506 ms


In [4]:
# slicing

a = np.array([2,4,6,7,8,5])
print(a[0:4],'\n')

b = np.random.randint(5,size=(2,3))
print(b,'\n')
print(b[0:2,1],'\n')
print(b[:1],'\n')
print(b[0,...],'\n')
print(a[::-1],'\n')

[2 4 6 7] 

[[3 4 1]
 [4 4 3]] 

[4 4] 

[[3 4 1]] 

[3 4 1] 

[5 8 7 6 4 2] 



In [5]:
# boolean indexing
a[a<5]

array([2, 4])

In [6]:
# array manipulation

#transpose
i = np.transpose(b)
print(i,'\n')
print(i.T,'\n')

#changing array shape

print(np.ravel(b),'\n')
print(a.reshape(2,3),'\n')
print(np.resize(a,(3,2)),'\n')

# adding/removing elements
a1 = np.append(a,(2,6))
print(a1,'\n')
a1 = np.insert(a1,7,100)
print(a1,'\n')
print(np.delete(a1,[7]),'\n')

[[3 4]
 [4 4]
 [1 3]] 

[[3 4 1]
 [4 4 3]] 

[3 4 1 4 4 3] 

[[2 4 6]
 [7 8 5]] 

[[2 4]
 [6 7]
 [8 5]] 

[2 4 6 7 8 5 2 6] 

[  2   4   6   7   8   5   2 100   6] 

[2 4 6 7 8 5 2 6] 



In [7]:
#combining arrays
a = np.array([[2,3],[4,5]])
b = np.array([[9,8],[7,6]])

print(a,' = a\n')
print(b,' = b\n')
print(np.concatenate((a,b),axis=1),'\n')  # axis = 0 for vstack
print(np.vstack((a,b)),'\n')
print(np.row_stack((a,b)),'\n')
print(np.r_[a,b],'\n')

print(np.hstack((a,b)),'\n')
print(np.column_stack((a,b)),'\n')             #same
print(np.c_[a,b],'\n')                         #same


[[2 3]
 [4 5]]  = a

[[9 8]
 [7 6]]  = b

[[2 3 9 8]
 [4 5 7 6]] 

[[2 3]
 [4 5]
 [9 8]
 [7 6]] 

[[2 3]
 [4 5]
 [9 8]
 [7 6]] 

[[2 3]
 [4 5]
 [9 8]
 [7 6]] 

[[2 3 9 8]
 [4 5 7 6]] 

[[2 3 9 8]
 [4 5 7 6]] 

[[2 3 9 8]
 [4 5 7 6]] 



In [8]:
# splitting arrays
temp = np.random.randint(10,size=(3,6))
long = np.copy(temp)
print(long,'\n')
print(np.vsplit(long,1),'\n')
print(np.hsplit(long,3),'\n')

[[7 8 6 7 4 6]
 [3 1 3 5 5 5]
 [2 6 8 8 8 7]] 

[array([[7, 8, 6, 7, 4, 6],
       [3, 1, 3, 5, 5, 5],
       [2, 6, 8, 8, 8, 7]])] 

[array([[7, 8],
       [3, 1],
       [2, 6]]), array([[6, 7],
       [3, 5],
       [8, 8]]), array([[4, 6],
       [5, 5],
       [8, 7]])] 



In [9]:
a = np.random.randint(10,size=(6,6))
np.savetxt('rand_array.txt',a,delimiter=" ")
np.savetxt('rand_array.csv',a,delimiter=',')
print(a)

[[8 7 2 5 1 4]
 [5 6 1 9 4 4]
 [7 5 8 3 3 2]
 [7 0 5 3 0 5]
 [4 2 2 1 1 2]
 [2 1 2 5 8 5]]


In [10]:
b = np.loadtxt('rand_array.txt')
c = np.genfromtxt('rand_array.csv',delimiter=',')
print(np.shape(b),'\n')
print(b,'\n')
print(np.shape(c),'\n')
print(c,'\n')

(6, 6) 

[[ 8.  7.  2.  5.  1.  4.]
 [ 5.  6.  1.  9.  4.  4.]
 [ 7.  5.  8.  3.  3.  2.]
 [ 7.  0.  5.  3.  0.  5.]
 [ 4.  2.  2.  1.  1.  2.]
 [ 2.  1.  2.  5.  8.  5.]] 

(6, 6) 

[[ 8.  7.  2.  5.  1.  4.]
 [ 5.  6.  1.  9.  4.  4.]
 [ 7.  5.  8.  3.  3.  2.]
 [ 7.  0.  5.  3.  0.  5.]
 [ 4.  2.  2.  1.  1.  2.]
 [ 2.  1.  2.  5.  8.  5.]] 

