In [1]:
# memory usage and time stamping - #1
#importing lib
import numpy as np
import time 
import sys

In [2]:
# Memory usage
# python list
py_list = range(1000)                                                    #python list
print('python list takes',sys.getsizeof(7)*len(py_list),'bytes')         # 7* can be any number

#numpy array
np_array = np.arange(1000)
print('numpy array takes',np_array.size*np_array.itemsize,'bytes')
np_array.itemsize,np_array.size

python list takes 28000 bytes
numpy array takes 4000 bytes


(4, 1000)

In [3]:
# Time taken by numpy and python list
array_size = 10000000                                                   # 10 million ,a consideribly large size helps understand the time difference better

# Python list
py_list1 = range(array_size)
py_list2 = range(array_size)

py_start = time.time()                                                  # capturing a time instance(similar to a stop watch)
result = [(x + y) for x,y in zip(py_list1,py_list2)]                    # performing addiiton of the two lists
py_end = time.time()                                                    # capturing a second  time instance(the difference gives the time taken for the operation)
print('time taken for python list :',(py_end - py_start) * 1000,'ms')   # By default the time is in seconds *1000 coverts it to milliseonds

# numpy array
np_array1 = np.arange(array_size)
np_array2 = np.arange(array_size)

np_start = time.time()
result = np_array1 + np_array2
np_end = time.time()
print('time taken for numpy array :',(np_end - np_start) * 1000,'ms')

time taken for python list : 874.352216720581 ms
time taken for numpy array : 152.37975120544434 ms


In [2]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/oe_WEyntm8Y?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [4]:
# Creating arrays - #2.1
array_a = np.array([1,2,3])                                              # create 1D array
array_b = np.array([[2,4,5],[5,3,9]],dtype=float)                        # creating a 2x3 matrix with values as type float
array_c = np.array([[(3.2,5,6),(4.1,7,9)],[(2,4,5),(7,4,9)]],dtype=float)# creating multple arrays with data type as float

print(array_a,'= array a (1D array)\n')
print(array_b,'= array b (2D array)\n')
print(array_c,'= array c (multiple arrays)')

[1 2 3] = array a (1D array)

[[ 2.  4.  5.]
 [ 5.  3.  9.]] = array b (2D array)

[[[ 3.2  5.   6. ]
  [ 4.1  7.   9. ]]

 [[ 2.   4.   5. ]
  [ 7.   4.   9. ]]] = array c (multiple arrays)


In [3]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Y9jZJ9edRWw?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [5]:
# Creating arrays - #2.2
# Creating arrays with place holders

zeros_array = np.zeros((3,3))                                            # creates a 3x3 matrix with zeros
ones_array = np.ones((3,4))                                              # creates a 3x4 array with ones
empty_array = np.empty((3,4))                                            # creates an empty array with dimensions 3x4
eye_array = np.eye(3)                                                    # creates an identity matrix of 3x3
random_array = np.random.random((3,2))                                   # creates a 3x3 array with random variables
full_array = np.full((2,2),6)                                            #creates an array with constant number 6

print(zeros_array,'= zeros array \n')
print(ones_array,'= ones array\n')
print(empty_array,'= empty array\n')
print(eye_array,'= identity array\n')
print(random_array,'= random array \n')
print(full_array,'= constant array \n')

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] = zeros array 

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] = ones array

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] = empty array

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] = identity array

[[ 0.47462207  0.79551999]
 [ 0.79322542  0.27434081]
 [ 0.97502781  0.13093778]] = random array 

[[6 6]
 [6 6]] = constant array 



In [5]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/cf5XyJ5hNQ4?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [6]:
# Array inspection - #3

ins_array = np.array([[3,2,1,4],[7,5,9,2]])                                  # creating a 2x4 array(inspection array)

print(ins_array,'= Array')                                                   #displaying the array
print('\n',ins_array.shape,'= shape the array / dimensions of the array\n')
print(len(ins_array),'length of the array\n')
print(ins_array.ndim,'= number of array dimensions\n')
print(ins_array.size,'= number of array elements\n')
print(ins_array.dtype,'= data type of the array elements\n')
print(ins_array.dtype.name,'= name of the data type\n')
print(ins_array.astype(float),'= convert an array to a different type\n') 

[[3 2 1 4]
 [7 5 9 2]] = Array

 (2, 4) = shape the array / dimensions of the array

2 length of the array

2 = number of array dimensions

8 = number of array elements

int32 = data type of the array elements

int32 = name of the data type

[[ 3.  2.  1.  4.]
 [ 7.  5.  9.  2.]] = convert an array to a different type



In [7]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/mpqGel6QqIQ?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [7]:
# Arithmetic opreations - $4.1

array_a = np.array([[2,3],[5,7]])                                          # creating array A 2x2
array_b = np.array([[4,2],[6,8]])                                          # creating array B 2x2

print(array_a,' = array A\n')
print(array_b,' = array B\n')

print(array_a - array_b,' = subtraction\n')                                #subtracting two arrays normal operation
print(np.subtract(array_a,array_b),'= subtraction using numpy\n')

print(array_a + array_b,' = addition\n')                                   #addition two arrays normal operation
print(np.add(array_a,array_b),'= addition using numpy\n')

print(array_a / array_b,' = division\n')                                   #dividing two arrays normal operation
print(np.divide(array_a,array_b),'= division using numpy\n')

print(array_a * array_b,' = multiplication\n')                             #multiplying two arrays normal operation
print(np.multiply(array_a,array_b),'= multiplication using numpy\n')

[[2 3]
 [5 7]]  = array A

[[4 2]
 [6 8]]  = array B

[[-2  1]
 [-1 -1]]  = subtraction

[[-2  1]
 [-1 -1]] = subtraction using numpy

[[ 6  5]
 [11 15]]  = addition

[[ 6  5]
 [11 15]] = addition using numpy

[[ 0.5         1.5       ]
 [ 0.83333333  0.875     ]]  = division

[[ 0.5         1.5       ]
 [ 0.83333333  0.875     ]] = division using numpy

[[ 8  6]
 [30 56]]  = multiplication

[[ 8  6]
 [30 56]] = multiplication using numpy



In [8]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/6rRc_6XFzdM?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [8]:
# Arithmetic opreations - $4.2
print(array_a,'= array A\n')

print(np.exp(array_a),' = exponentitation\n')                           # returns the exponent of the array
print(np.sqrt(array_a),'= Square root\n')                               # returns the square root of the array
print(np.sin(array_a),' = sines\n')                                     # prints the sines of the array
print(np.cos(array_a),' = cosine\n')                                    # returns element wise cosine
print(np.log(array_a),' = natural logarithm\n')                         # returns element wise natural logarithm
print(array_a.dot(2),' = dot product\n')                                # dot product of the array

[[2 3]
 [5 7]] = array A

[[    7.3890561     20.08553692]
 [  148.4131591   1096.63315843]]  = exponentitation

[[ 1.41421356  1.73205081]
 [ 2.23606798  2.64575131]] = Square root

[[ 0.90929743  0.14112001]
 [-0.95892427  0.6569866 ]]  = sines

[[-0.41614684 -0.9899925 ]
 [ 0.28366219  0.75390225]]  = cosine

[[ 0.69314718  1.09861229]
 [ 1.60943791  1.94591015]]  = natural logarithm

[[ 4  6]
 [10 14]]  = dot product



In [9]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/9AAayMNmyS8?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [9]:
# comparison and aggregate #5
# Comparision

print(array_a,' = array A\n')
print(array_b,' = array B\n')

print(array_a == array_b,' = comparison\n')                                # element wise comparison
print(array_a<5 ,' = comparison\n')                                        # prints true for all values < 5
print('array A and array B are equal = ',np.array_equal(array_a,array_b))  # array wise comparison

[[2 3]
 [5 7]]  = array A

[[4 2]
 [6 8]]  = array B

[[False False]
 [False False]]  = comparison

[[ True  True]
 [False False]]  = comparison

array A and array B are equal =  False


In [10]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/LBYxxBUijtk?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [10]:
# Aggregate functions

print(array_a,' = array A\n')                                             # display array
print(array_a.sum(),'--- sum\n')                                          # array wise sum 
print(array_a.min(),'--- minimum value\n')                                # array wise minimum value
print(array_a.max(axis=0),'--- max value\n')                              # maximum value of an array row
print(array_a.mean(),'--- mean\n')                                        # mean of the array
print(array_a.std(),'--- std\n')                                          # standard deviation of the array    

[[2 3]
 [5 7]]  = array A

17 --- sum

2 --- minimum value

[5 7] --- max value

4.25 --- mean

1.92028643697 --- std



In [11]:
# sorting arrays #6

rand_array =np.random.random((8,3))                                      # Creating a 8x1 array of random variables

print(rand_array,' = random variable array\n')                           # displaying array
print(np.sort(rand_array,axis=0),' = sorting of array colom wise')       # By default the sorting is applied on row wise axis = 1 changes it to colom wise   

[[ 0.65564201  0.65019195  0.68340442]
 [ 0.12041782  0.22482636  0.26998412]
 [ 0.71882749  0.43499451  0.26807501]
 [ 0.84161504  0.07437956  0.45591895]
 [ 0.78244078  0.31479992  0.3246319 ]
 [ 0.54346314  0.86662959  0.41075349]
 [ 0.91351814  0.0184932   0.49684653]
 [ 0.02273507  0.07261549  0.662182  ]]  = random variable array

[[ 0.02273507  0.0184932   0.26807501]
 [ 0.12041782  0.07261549  0.26998412]
 [ 0.54346314  0.07437956  0.3246319 ]
 [ 0.65564201  0.22482636  0.41075349]
 [ 0.71882749  0.31479992  0.45591895]
 [ 0.78244078  0.43499451  0.49684653]
 [ 0.84161504  0.65019195  0.662182  ]
 [ 0.91351814  0.86662959  0.68340442]]  = sorting of array colom wise


In [11]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/JUd_PIr91e0?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [12]:
# Subsetting #7

array_a = np.random.random(9)                                           # create an array of 9 elements
print(array_a,' = array A\n')                                           # Display array
print('the 7th element is = ',array_a[6])                               # selecting the 7th element in array A

array_b = np.random.randint(5, size=(2,5))                              # create random array 
print(array_b,' = array B\n')                                           # Display array
print('2nd coloum 2nd row = ',array_b[1,1])                             # selecting the element from 2nd row 2nd coloumn

[ 0.41377433  0.42835517  0.38716187  0.02326561  0.89317456  0.58834095
  0.93097992  0.05222874  0.90970461]  = array A

the 7th element is =  0.930979919349
[[2 0 4 1 3]
 [1 3 3 1 1]]  = array B

2nd coloum 2nd row =  3


In [12]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/gjbQv8ncl8s?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [13]:
# slicing #8

temp_array = np.random.randint(10,size=(2,3))                            # Create a random array and store it in a temp array 
#array_a = temp_array                                                    # assign array A to the temp array
print(array_a,' = array A\n')                                            # display array A
print('the first 4 elements are = ',array_a[0:4],'\n')                   # Display till element 4
print(array_a[::-1],' = reversed array A\n')                             # reverse the array A  

#array_b = temp_array                                                    # assign array B to the temp array with dimensions 2x3
print(array_b,' = array B\n')                                            # Display array B

print(array_b[0:2,1],'= row 0 & 1 in coloumn 1 \n')                      # Select items at rows 0 and 1 in coloumn 1
print(array_b[:1],' = row 0 \n')                                         # Select all items at row 0

[ 0.41377433  0.42835517  0.38716187  0.02326561  0.89317456  0.58834095
  0.93097992  0.05222874  0.90970461]  = array A

the first 4 elements are =  [ 0.41377433  0.42835517  0.38716187  0.02326561] 

[ 0.90970461  0.05222874  0.93097992  0.58834095  0.89317456  0.02326561
  0.38716187  0.42835517  0.41377433]  = reversed array A

[[2 0 4 1 3]
 [1 3 3 1 1]]  = array B

[0 3] = row 0 & 1 in coloumn 1 

[[2 0 4 1 3]]  = row 0 



In [13]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/AL_j0SY0c04?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [14]:
# boolean indexing #9

print(array_b,' = array B\n')                                            # Disaplay array B
print(array_b[array_b<3],'\n')                                           # Display all elements in array B less than 3

[[2 0 4 1 3]
 [1 3 3 1 1]]  = array B

[2 0 1 1 1 1] 



In [14]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/mHfdohG0mDs?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [15]:
# array manipulation #10

# Transposing
print(array_b,' = array B\n')                                            # Dispplay array B
print(np.transpose(array_b),' = transposed array B(numpy)\n')            # numpy function for transposing an array
print(array_b.T,' = transposed array B\n')                               # transposing array 

# Changing shape of the array
print(array_a,' = array A\n')
print(array_b,' = array B\n')
print(np.ravel(array_b),' = flattened array B\n')                        # reduce from n-Dimensions to 1D array
#print(array_a.reshape(2,4),' = new array A\n')                           # reshapes an array but does not change data
print(np.resize(array_a,(4,2)),' = new array A(numpy,resize)\n')         # returns a new array with the size 4x2

# adding/removing elements 

array_1 = np.append(array_a,(3,8))                                       # adding items(3,2) to array 1
print(array_a,' = array A\n')                                            # Display array A
print(array_1,' = array 1(append)\n')                                    # Display array 1
array_1 = np.insert(array_1,7,100)                                       # insert value 100 at position/element 7 in array_1
print(array_1,' = array 1(insert)\n')                                    # Display array 1  
print(np.delete(array_1,[7]),' = array 1(delete)\n')                     # deletes values of element 7 in array 1 

[[2 0 4 1 3]
 [1 3 3 1 1]]  = array B

[[2 1]
 [0 3]
 [4 3]
 [1 1]
 [3 1]]  = transposed array B(numpy)

[[2 1]
 [0 3]
 [4 3]
 [1 1]
 [3 1]]  = transposed array B

[ 0.41377433  0.42835517  0.38716187  0.02326561  0.89317456  0.58834095
  0.93097992  0.05222874  0.90970461]  = array A

[[2 0 4 1 3]
 [1 3 3 1 1]]  = array B

[2 0 4 1 3 1 3 3 1 1]  = flattened array B

[[ 0.41377433  0.42835517]
 [ 0.38716187  0.02326561]
 [ 0.89317456  0.58834095]
 [ 0.93097992  0.05222874]]  = new array A(numpy,resize)

[ 0.41377433  0.42835517  0.38716187  0.02326561  0.89317456  0.58834095
  0.93097992  0.05222874  0.90970461]  = array A

[ 0.41377433  0.42835517  0.38716187  0.02326561  0.89317456  0.58834095
  0.93097992  0.05222874  0.90970461  3.          8.        ]  = array 1(append)

[  4.13774325e-01   4.28355170e-01   3.87161866e-01   2.32656111e-02
   8.93174561e-01   5.88340948e-01   9.30979919e-01   1.00000000e+02
   5.22287449e-02   9.09704606e-01   3.00000000e+00   8.00000000e+00]  = ar

In [15]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/uDiNB55nBZU?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [16]:
# combining Arrays #11

array_a = np.array([[2,3],[4,5]])                                         # create a 2x2 array A 
array_b = np.array([[9,8],[7,6]])                                         # create a 2x2 array B

print(array_a,' = array A\n')                                             # Display array A
print(array_b,' = array B\n')                                             # Display array B

print(np.concatenate((array_a,array_b),axis=1),' = concatenated array\n') # concatenates array A and array B 
print(np.vstack((array_a,array_b)),' = Vstack(numpy)\n')                  # stacking arrays row wise - method 1
print(np.row_stack((array_a,array_b)),' = row stacking\n')                # stacking arrays row wise - method 2
print(np.r_[array_a,array_b],' = row stacking(r_)\n')                     # stacking arrays row wise - method 3


print(np.hstack((array_a,array_b)),' = Vstack(numpy)\n')                  # stacking arrays coloumn wise - method 1
print(np.column_stack((array_a,array_b)),' = coloumn stacking\n')         # stacking arrays coloumn wise - method 2
print(np.c_[array_a,array_b],' = coloumn stacking(c_)\n')                 # stacking arrays coloumn wise - method 3

[[2 3]
 [4 5]]  = array A

[[9 8]
 [7 6]]  = array B

[[2 3 9 8]
 [4 5 7 6]]  = concatenated array

[[2 3]
 [4 5]
 [9 8]
 [7 6]]  = Vstack(numpy)

[[2 3]
 [4 5]
 [9 8]
 [7 6]]  = row stacking

[[2 3]
 [4 5]
 [9 8]
 [7 6]]  = row stacking(r_)

[[2 3 9 8]
 [4 5 7 6]]  = Vstack(numpy)

[[2 3 9 8]
 [4 5 7 6]]  = coloumn stacking

[[2 3 9 8]
 [4 5 7 6]]  = coloumn stacking(c_)



In [16]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/XcuZlbGBB7Y?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [17]:
# splitting arrays #12

rand_array = np.random.randint(10,size=(3,6))                             # create a 3x6 array with random numbers
array_1 = np.copy(rand_array)                                             # copy rand_array to array_1

print(array_1,' = array 1\n')                                             # Display array 1
print(np.vsplit(array_1,1),' = vsplit array\n')                           # split the array vertically at the 1st index
print(np.hsplit(array_1,3),' = hsplit array\n')                           # split the array horizontlly at the 3rd index

[[2 7 4 9 0 4]
 [7 3 7 0 9 6]
 [9 5 9 4 9 7]]  = array 1

[array([[2, 7, 4, 9, 0, 4],
       [7, 3, 7, 0, 9, 6],
       [9, 5, 9, 4, 9, 7]])]  = vsplit array

[array([[2, 7],
       [7, 3],
       [9, 5]]), array([[4, 9],
       [7, 0],
       [9, 4]]), array([[0, 4],
       [9, 6],
       [9, 7]])]  = hsplit array



In [17]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/ESTVjKZ9VP4?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>

In [18]:
# saving and loading files #13

temp_array = np.random.randint(10,size=(6,6))                             # create a random array and store it in temp
#array_a = np.copy(temp_array)                                            # copy temp array to array A
np.savetxt('array_A.txt',array_a,delimiter=" ")                           # save array A in a .txt file with delimiter as " "(space)
np.savetxt('array_A.csv',array_a,delimiter=',')                           # save array A in a .csv file with delimiter as ',' (comma)
print(array_a,' = array A\n')                                             # Display array A 

# loading files

array_b = np.loadtxt('array_A.txt')                                       # load array_A.txt into array_b
array_c = np.genfromtxt('array_A.csv',delimiter=',')                      # load values of array_A.txt into array_c 
print(array_b,' = array B(.txt file)\n')                                  # Display array B (loaded from txt file)
print(array_c,' = array C(.csv file)\n')                                  # Display array C (loaded from csv file)

[[2 3]
 [4 5]]  = array A

[[ 2.  3.]
 [ 4.  5.]]  = array B(.txt file)

[[ 2.  3.]
 [ 4.  5.]]  = array C(.csv file)



In [18]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/TFryxV0hhqE?list=PLRzT9zpsdiLCnM4w0u5LmNZ6OKg9lENS0" frameborder="0" allowfullscreen></iframe>